### PR TITLE
Enabling multiplayer AI after setting position

### PR DESCRIPTION
**Pull request by MichaelRThompson**
Update from NASA develop

### CODE REVIEW

**Comment by MichaelRThompson** [comment]
Whoops.  Still new to GitHub.  This can be deleted.

**Comment by MichaelRThompson** [comment]
Based on comments in #114 , HandlePosi should enable the AI after setting the a/c position.  The code currently enables the AI before setting the position.

**Comment by MichaelRThompson** [comment]
And I'm not sure, but I wonder if this could have anything to do with #115

**Comment by jason-watkins** [comment]
Yep, that's definitely backwards. Thanks for the fix. I will see if I can reproduce #115 with and without this patch included. I wouldn't think it would be related, but it's possible.

**Comment by MichaelRThompson** [comment]
I keep second guessing myself about this commit.  Maybe you can clear some things up for me.

I know for sure:
`override_planepath` turns off the physics sim for any one of the a/c

I don't know for sure:
Does `override_planepath` automatically also write to `override_plane_ai_autopilot`?  The documentation [here](http://www.xsquawkbox.net/xpsdk/mediawiki/MovingThePlane#Controlling_AI_Aircraft_in_X-Plane_8_and_9) makes it seem like it _might_ be the case, but I'm not sure.

But what I'm really getting at:
So even if the AI is disabled by `override_planepath` , why is in re-enabled in the `HandlePosi` function?  This function never writes to `override_planepath` directly, and neither does `SetPosition`, `SetOrientation`, or `SetGear`, the only relevant functions called inside.  The more I think about it, the more I think that this commit doesn't actually change anything, and in fact, a more appropriate place to enable the AI would be when the simulation is unpaused.

Am I missing something here @jason-watkins ?  Is there a documented reason that the AI was enabled here when the position is changed?

**Pull request merged**
