### PR TITLE
Version 1.3-rc.1

### PR DESCRIPTION
**Pull request by jason-watkins**
Proposed release notes:

## General Changes
- Update the sendPOSI command to use 64 bit floats (#111)
- Updated XPlane SDK to version 2.1.3

## New Features
- Added ability to pause individual aircraft (#114)
- Added sendCOMM function, which makes it possible to send X-Plane commands from the client (#120)

## Changes to the X-Plane Connect Plugin
- Minor improvements to the handling of landing gear by the SetGear and HandlePOSI functions

## Bug Fixes
- Rolled back Java version to 1.7 due to some reports of MATLAB incompatability
- Fixed a bug with re-enabling the AI for NPC planes after setting their position (#118)

### CODE REVIEW

**Comment by rthaenert** [comment]
While testing this on Mac OS:
The sendCOMM functionality which was done in PR #120 seems to be missing in this branch.

If i can help you with Mac binaries let me know.

**Comment by JanC** [comment]
Hi,
is there any ETA when the 1.3 will be released?

**Comment by jason-watkins** [comment]
Unfortunately I don't have a timeline right now. I don't feel comfortable accepting third party binaries into the repo, but I do have an alternative solution in mind... If anyone cares to submit a PR to set up any continuous integration service/services that are free for open source projects and can be configured to produce the necessary binaries, I'll gladly take the binaries produced by that service.

It's on my todo list to do this myself, but I have an unfortunate lack of bandwidth for personal projects these days, and since I don't currently have any NASA funding for XPC, any work I do on the project has to be on my own time.

**Comment by JanC** [comment]
Hi Jason,
I totally understand. I was also thinking about setting up a CI for this. While I’m familiar with macOS and Linux CI, I’m not sure how Windows would work. I’ll try to find some time to investigate.
cheers

**Comment by tukan68** [comment]
Hi all,
Could travis-ci.org be a solution? According to the documentation, they can release a build to GitHub. Build servers are available for Mac, Windows and various Linux.

**Comment by jason-watkins** [comment]
Yep, I think Travis would work. I actually had another project set up to use it, but unfortunately that project is no longer open source so I can't link to it as a starting point. Travis's Windows support is also pretty new, so I was actually using Tavis for Linux/Mac and Appveyor for Windows on said project.

Travis would be ideal for me in the sense that I'm familiar with it so it's easy for me to review the PR. It's also convenient that it should be a one-stop-shop for all OSes we support now. That said, I left my comment above open-ended because I don't necessarily want to discourage other solutions. If I get a PR that uses another service I'm happy to review that too.

**Comment by JanC** [comment]
I already started to work on a Travis setup. I’ll make a PR

**Comment by sybohy** [comment]
To add to @rthaenert comments, the SendComm functionality [was erased during a force push to the develop branch](https://github.com/nasa/XPlaneConnect/compare/1eccd5fe633aded3590b91193036661f71bbb0b2..e1105206a36b33e9f151cc1d45e881228a158824). The release notes incorrectly make a reference to #120. The scope of that feature was fairly limited so my recommendation would be to `git cherry-pick`. I'm happy to try to add it back in, but if it's somewhat useless if we don't yet have a CI pipeline. @JanC any update here?

**Comment by JanC** [comment]
The CI is technically working but @jason-watkins cannot grant the access to the nasa repo so he is running it in [his fork](https://github.com/jason-watkins/XPlaneConnect/)

**Comment by jason-watkins** [comment]
Whoops... not sure how that happened. If someone wants resubmit the PR I'll re-merge it that way. Otherwise I'll do it myself when I have a chance.

**Comment by sybohy** [comment]
No worries, and this is why I usually [disable force-push](https://help.github.com/en/enterprise/2.16/admin/developer-workflow/blocking-force-pushes-to-a-repository) on my github repos  😄 

I will take care of submitting a new PR.

**Comment by jason-watkins** [comment]
Yeah, I actually have other repos set up to entirely disable pushes to master and develop so that the only way code hits those branches is through a proper PR. This is a good reminder for me to ask for that to be enabled here too.

**Pull request merged**
