### PR TITLE
fix xcode compile error

### PR DESCRIPTION
**Pull request by flyingk**
Xcode 9 complains about the abs() function without the cmath header. Works fine adding it.

### CODE REVIEW

**Comment by jason-watkins** [comment]
Hi Kai,

We only accept pull requests against the `develop` branch, which I believe has already fixed this issue. Could you check whether you still have this issue on that branch and re-submit the PR there if so?

Thanks,
Jason

**Comment by flyingk** [comment]
Hi Jason, ok saw it and it also fixes it. However, I would prefer the header solution over this strange call to abs()... Do you still need Mac binaries? Can run it now.

**Comment by jason-watkins** [comment]
If including <cmath> will get rid of the weird function pointer cast, I'm happy to accept that PR.

We need to produce the binaries in-house, I just haven't gotten around to it. It's not that *I* don't trust you, but I would be in an awful lot of trouble if I accepted a PR with a malicious binary in it.

**Comment by flyingk** [comment]
OK, sure.

**Pull request closed without merging**
