### PR TITLE
Python3: Import sendCOMM to python3

### PR DESCRIPTION
**Pull request by Jaaaky**

### CODE REVIEW

**Comment by sanderdatema** [comment]
This has already been done in #217 and #219, but @jason-watkins still needs to merge this from `develop` into `master`. But it takes a very long time appearently... 😀

**Comment by jason-watkins** [comment]
Ah, thanks for pointing that out. Yes, things move slowly here for a couple of reasons. I no longer receive funding to work on this project, so any management I do is done on my own time. It is still a NASA project though, and merging to master means an official "release", which NASA requires a certain amount of administrative work to authorize. Hopefully you can understand that I'm not all that highly motivated to fill out forms on my time off of work!

**Comment by sanderdatema** [comment]
@jason-watkins That explains quite a bit. However, we're quite a few PR's behind and there is no working Mac binary.
What if we fork the project and move on from there? Since NASA doesn't fund this anymore? It's a good plugin and it would be a waste to see it die because of bureaucracy.
What do you think, @jason-watkins, it's an open source license, so it should be doable, right?

**Comment by jason-watkins** [comment]
I have thought about forking before. I'm not militantly opposed to it, but I do wonder about the discoverability of the fork. There are a couple of things I want to try first. The main one is implementing GitHub actions. Right now, producing a build is a tedious task that involves my personal azure account and pushing changes back and forth to my personal fork. If I had GitHub actions set up where I could crate a GitHub release with a couple of clicks after merging a PR, that would go a long way towards making maintenance manageable.

If I had that in place, then I think we're long overdue for a proper merge to master and release. From there, I think the rate of change is slow enough that continuing my pattern of producing a "Release Candidate" in GitHub that tracks develop would work reasonably well. (I might even be able to get away with making develop the default branch).

**Comment by sanderdatema** [comment]
Yeah, I can totally understand what you're saying.
I'll fork the project (just for myself I mean) and see if I can fiddle around with the Github actions. I'll let you know.

**Pull request closed without merging**
