### PR TITLE
Version 1.0

### PR DESCRIPTION
**Pull request by jason-watkins**
All features I had for 1.0 are complete, and I am tracking no new bugs.

Still need to update plugin binaries for all platforms and run unit tests on Linux/Mac.

### CODE REVIEW

**Comment by teubert** [comment]
My github client seems to have problem with the '/' in the name. It seems to have resolved this by creating another branch called release-1.0. Lets use that naming scheme for future branches so we don't have this problem in the future. I'll commit from the command line from now on so we don't have any more messy pulls like the ones above.

**Comment by jason-watkins** [comment]
Duly noted. Since those pulls are *quite* messy, I'm inclined close this pull request, rename the branch, clean up the commit history, and re-open the pull request on the `release-1.0` branch. Is that OK with you?

**Comment by teubert** [comment]
Yes, I think that would be good.

Thanks,
Chris


On Apr 24, 2015, at 4:05 PM, Jason Watkins <notifications@github.com<mailto:notifications@github.com>> wrote:


Duly noted. Since those pulls are quite messy, I'm inclined close this pull request, rename the branch, clean up the commit history, and re-open the pull request on the release-1.0 branch. Is that OK with you?

**Comment by jason-watkins** [comment]
Cleaned things up a bit and trying again in #59.

**Pull request closed without merging**
