### PR TITLE
V1.2.1

### PR DESCRIPTION
**Pull request by teubert**
Various bugfixes, namely:

- SetPosition now updates the aircraft's orientation after moving the aircraft, should improve performance
- Fixed Sudden aircraft crash after "pauseSim" command (#91)
- Replaced istrue with isequal in Matlab client
- Fixed use of incorrect readData java call in Matlab readData function
- Removed use of C99 for-loop initialization in c client
- Removed unused dead-code
- Updated Copyright year
- Replaced incorrect use of time.h with sys/time.h for Linux/Mac
- Fixed error checking in c readData function
- Updated C client test project to build on VS 2015
- Fixed typo in readDATA error message

### CODE REVIEW

**Comment by teubert** [comment]
Tested on Red Hat Linux v6.9, OS X 10.11.6, and Windows 7.

**Comment by jason-watkins** [comment]
I get a few tests failing on Windows 10 that I don't really have time to dig into. Are you seeing all tests pass for the C client on Windows 7?

**Comment by jason-watkins** [comment]
Also, what's the reason for commit 9bb5f99f372b07fcb872bdd082345aa691140e23? Curious what platform isn't allowing variable declaration inside the loop, but accepts mixed declarations and initializations.

**Comment by teubert** [comment]
@jason-watkins: Thanks for testing this out on your machine. Sorry for the delay, I was on travel. Now I'm back and can look further into this.

I'm pretty sure all the tests passed for the C Client on Windows 7, I will double check later. Can you tell me which tests are failing on Windows 10.

Also 9bb5f99 was added specifically for Red Hat. The setup for the group's server was giving this error.

**Comment by teubert** [comment]
@jason-watkins I have a theory! 

Are you getting the errors "[getDREFs] ERROR: Read operation failed."? If so, it seems that the tests are being sent faster than XPCPlugin can handle them. In that case we have it clear the message buffer (close and open the sockets). When this happens, those messages are lost and I receive those error messages. 

I'm occasionally receiving these messages testing on mac. Unfortionately, If we dont have it reset the socket, either the sim will fall far behind (if we keep the per cycle message limit), or the sim could freeze (if we remove the limit) or run very slow. Adding a small delay between the tests fixes this issue for the test, but we should think about ways we could notify the user that too many commands are being received (maybe a message on the screen). Let's discuss that this summer.

In the meantime, when you have some free time could you try the unit tests I just checked in and let me know if that change fixes the issue you were having with the tests?

**Comment by jason-watkins** [comment]
With the latest commit, every test passes except for the VIEW test, which I think has never actually worked.

I did need to tweak the `window.h` include in Test.h to compile successfully in Visual Studio 2015.

All in all, I am comfortable merging this.

**Comment by teubert** [comment]
Great. Thanks, @jason-watkins. I realize though that commit 10f3ce2 changes the plugin code, so this now needs updated Linux and Windows binaries. I'll try to provide those and rerun the tests today.

**Pull request merged**
