### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by jason-watkins**
## General Changes
 - All of the example scripts now check that they are connected before
   sending commands.
 - The "Docs" folder has been removed from the repository. All information
   previously documented there has been transfered to the wiki.

## New Features
 - A Python client has been added.
 - The sendCTRL command now supports setting speed-brakes.
 - The sendDREF command has been augmented with a sendDREFs variant that
   supports setting multiple datarefs at once.
 - A sendVIEW command has been added that supports setting the camera view in
   X-Plane.

#### Enhancements

 - Greatly improved logging efficiency by keeping a single open file
   descriptor for the entire program execution.
 - Improved consistency of includes. All C headers should now be included
   using the \<c*name*> style rather than "*name*.h" style.
 - Numerous methods and parameters that could be marked `const` have been.
 - Several value type string parameters have been replaced with const
   references.
 - Logging has been refactored to take the logging level as a method parameter.
 - Trace logging has been made substantially more comprehensive.
 - Handling of default values (-998, -999) has been centralized in the `DataManager::IsDefault` and `DataManager::GetDefaultValue` methods.

#### Bug Fixes
 - Fixed a bug where DataManager::SetGear would sometimes incorrectly log an
   error when passed a default value.
 - The flight loop callback registration handling has been moved to the
   enable/disable function pair instead of the start/stop pair. The plugin
   manager seems to be smart enough to only call callbacks for enabled
   plugins, but it still makes sense to unregister the callback completely
   while disabled.

## Changes to the C client
 - The unit test suite has been refactored. There is now one file per client
   function. This should make it much easier to maintain and expand test
   coverage in the future.

### CODE REVIEW

**Comment by teubert** [comment]
XPC Tests-MATLAB (Mac)
Test 1: Open/Close Test - SUCCESS
Test 2: TEXT Test - SUCCESS
Test 3: Request DREF Test - SUCCESS
Test 4: Send DREF Test - FAILURE
	Undefined variable socket.
Test 5: DATA Test - SUCCESS
Test 6: CTRL Test - SUCCESS
Test 7: POSI Test - SUCCESS
Test 8: WYPT Test - SUCCESS
Test 9: VIEW Test - FAILURE
	Assertion failed.
Test 10: Pause Test - SUCCESS
Test 11: setConn Test - FAILURE
	Java exception occurred: 
java.lang.ArrayIndexOutOfBoundsException: 6
	at gov.nasa.xpc.XPlaneConnect.getDREFs(XPlaneConnect.java:311)
Results Summary:
Passed: 8	Failed: 3

**Comment by teubert** [comment]
======================================================================
ERROR: test_sendView (__main__.XPCTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Tests.py", line 331, in test_sendView
    result = client.getDREF(dref)
  File "/Users/cteubert/Documents/Projects/XPC Project/XPlaneConnect/TestScripts/Python Tests/xpc.py", line 274, in getDREF
    return self.getDREFs([dref])[0]
  File "/Users/cteubert/Documents/Projects/XPC Project/XPlaneConnect/TestScripts/Python Tests/xpc.py", line 293, in getDREFs
    buffer = self.readUDP()
  File "/Users/cteubert/Documents/Projects/XPC Project/XPlaneConnect/TestScripts/Python Tests/xpc.py", line 69, in readUDP
    return self.socket.recv(16384)
timeout: timed out

======================================================================
ERROR: test_setCONN (__main__.XPCTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Tests.py", line 373, in test_setCONN
    client.setCONN(49055)
  File "/Users/cteubert/Documents/Projects/XPC Project/XPlaneConnect/TestScripts/Python Tests/xpc.py", line 95, in setCONN
    buffer = self.socket.recv(1024)
timeout: timed out

----------------------------------------------------------------------
Ran 15 tests in 0.274s

FAILED (errors=2)

**Comment by teubert** [comment]
XPC Tests-c (Mac) 
Running test VIEW... [readUDP] ERROR: Error reading socket
[getDREFs] ERROR: Read operation failed.
Test VIEW - FAILED
	Error: -1

**Comment by jason-watkins** [comment]
Since sendVIEW is a new feature, and it is taking some time to track down the issue, we are going to merge this as is and get sendVIEW working on all clients in the next release. See #75 for issue tracking on sendVIEW.

**Pull request merged**
